import './globals.css'
import { Poppins } from 'next/font/google'

const inter = Poppins({ weight: ["300", "400", "500", "600", "700"], subsets: ['latin'] })

export const metadata = {
  title: 'UnSplash-App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
